version: '3.8'


services:
  postgres:
    image: postgres
    container_name: library-container
    env_file:
     - ../../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/postgresql/data

volumes:
  postgres_data:

